name: EHML2024
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - jupyterlab
  - seaborn
  - pip
  - ipywidgets
  - scikit-learn
  - sktime
  - pip:
    - openpyxl
    - prophet